# Pandas

The `numpy` module is excellent for numerical computations, but to handle missing data or arrays with mixed types takes more work. The `pandas` module is currently the most widely used tool for data manipulation, providing high-performance, easy-to-use data structures and advanced data analysis tools.

In particular `pandas` features:

* A fast and efficient "DataFrame" object for data manipulation with integrated indexing;
* Tools for reading and writing data between in-memory data structures and different formats (CSV, Excel, SQL, HDF5);
* Intelligent data alignment and integrated handling of missing data;
* Intelligent label-based slicing, fancy indexing, and subsetting of large data sets;
* Aggregating or transforming data with a powerful "group-by" engine; 
* High performance merging and joining of data sets;
* Hierarchical axis indexing provides an intuitive way of working with high-dimensional data in a lower-dimensional data structure;
* Time series-functionalities;
* Highly optimized for performance, with critical code paths written in Cython or C.

In [4]:
import pandas as pd
import numpy as np

## Series

Series are completely equivalent to 1D array but with axis labels and the possibility to store heterogeneous elements. Of paramount importance are the time-series, used to define time evolutions of a phenomenon.

In [5]:
from string import ascii_lowercase as letters

# Creating a series, accessing indexes, values and values by their index 
xs = pd.Series(np.arange(10)*0.5, index=tuple(letters[:10]))
print ("xs:",'\n', xs,'\n')
print ("xs indexes:",xs.index,"    type: ", type(xs.values),'\n')
# Values of the Series are actually a numpy array
print ("xs values:", xs.values, "    type: ", type(xs.values),'\n')
print (xs['f'], xs.f, xs.h, '\n')
print (xs[['d', 'f', 'h']], '\n')
print (type(xs[['d', 'f', 'h']]), '\n')

xs:
 a    0.0
b    0.5
c    1.0
d    1.5
e    2.0
f    2.5
g    3.0
h    3.5
i    4.0
j    4.5
dtype: float64

xs indexes: Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], dtype='object')     type:  <class 'numpy.ndarray'>

xs values: [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]     type:  <class 'numpy.ndarray'>

2.5 2.5 3.5

d    1.5
f    2.5
h    3.5
dtype: float64

<class 'pandas.core.series.Series'>

In [6]:
# Extracting elements and operations: same as numpy array
print (xs[:3],'\n')
print (xs[7:], '\n')
print (xs[::3], '\n')
print (xs[xs>3], '\n')
print (np.exp(xs), '\n')    # cosi faccio l'esponenziale 
print (np.mean(xs), np.std(xs), '\n') # media e deviazione standard

a    0.0
b    0.5
c    1.0
dtype: float64

h    3.5
i    4.0
j    4.5
dtype: float64

a    0.0
d    1.5
g    3.0
j    4.5
dtype: float64

h    3.5
i    4.0
j    4.5
dtype: float64

a     1.000000
b     1.648721
c     2.718282
d     4.481689
e     7.389056
f    12.182494
g    20.085537
h    33.115452
i    54.598150
j    90.017131
dtype: float64

2.25 1.4361406616345072

In [7]:
# Series can be created from python dictionary too.
# Not that the elements can be whatever!
d = {'b' : 1, 'a' : 'cat', 'c' : [2,3]}
pd.Series(d)

b         1
a       cat
c    [2, 3]
dtype: object

A key difference between Series and ndarray is that operations between Series automatically align the data based on label. Thus, you can write computations without considering whether the Series involved have the same labels.

In [8]:
s = pd.Series(np.random.randn(5), index=tuple(letters[:5]))
print(s)
s = s[1:] + s[:-1]
print(s)

a    0.723340
b    1.349008
c    1.634879
d    2.031184
e   -1.224161
dtype: float64
a         NaN
b    2.698016
c    3.269759
d    4.062368
e         NaN
dtype: float64

### Time series

Time series are very often used to profile the behaviour of a quantity as a function of time. Pandas has a special index for that, `DatetimeIndex`, that can be created e.g. with the function `pd.data_range()`

In [9]:
# to define a date, the datetime module is very useful
import datetime as dt
date = dt.date.today()
print(date)

date = dt.datetime(2024,11,27,10,45,10,15)
print (date)

# otherwise, several notations are interpreted too
date = 'Nov 27 2024'
# or alternatively
date = '27/11/2024 10:45:00'
print (date)

days = pd.date_range(date, periods=7, freq='D')
print (days)

seconds = pd.date_range(date, periods=3600, freq='s')
print (seconds)

2024-12-27
2024-11-27 10:45:10.000015
27/11/2024 10:45:00
DatetimeIndex(['2024-11-27 10:45:00', '2024-11-28 10:45:00',
               '2024-11-29 10:45:00', '2024-11-30 10:45:00',
               '2024-12-01 10:45:00', '2024-12-02 10:45:00',
               '2024-12-03 10:45:00'],
              dtype='datetime64[ns]', freq='D')
DatetimeIndex(['2024-11-27 10:45:00', '2024-11-27 10:45:01',
               '2024-11-27 10:45:02', '2024-11-27 10:45:03',
               '2024-11-27 10:45:04', '2024-11-27 10:45:05',
               '2024-11-27 10:45:06', '2024-11-27 10:45:07',
               '2024-11-27 10:45:08', '2024-11-27 10:45:09',
               ...
               '2024-11-27 11:44:50', '2024-11-27 11:44:51',
               '2024-11-27 11:44:52', '2024-11-27 11:44:53',
               '2024-11-27 11:44:54', '2024-11-27 11:44:55',
               '2024-11-27 11:44:56', '2024-11-27 11:44:57',
               '2024-11-27 11:44:58', '2024-11-27 11:44:59'],
              dtype='datetime64[ns]', length=3600, freq='s')

To learn more about the frequency strings, please see this [link](http://pandas.pydata.org/pandas-docs/stable/timeseries.html#offset-aliases)


Timestamped data is the most basic type of time series data that associates values with points in time. For pandas objects it means using the points in time.

functions like `pd.to_datetime` can be used, for instance, when reading information as string from a dataset.

Timestamp is the pandas equivalent of python’s Datetime and is interchangeable with it in most cases.

In [10]:
tstamp = pd.Timestamp(dt.datetime(2020, 11, 9))

# internally it counts the nanoseconds from January 1st 19
#tstamp = pd.Timestamp(dt.datetime(1970, 1, 1, 0, 0, 0, 1))
print(tstamp.value)

# when creating a timestamp the format can be explicitly passed
ts = pd.to_datetime('2010/11/12', format='%Y/%m/%d')
print (type(ts))
print (ts.value)
ts = pd.to_datetime('12-11-2010 00:00', format='%d-%m-%Y %H:%M')
print (ts)
print (ts.value)

1604880000000000000
<class 'pandas._libs.tslibs.timestamps.Timestamp'>
1289520000000000000
2010-11-12 00:00:00
1289520000000000000

A standard series can be created and (range of) elements can be used as indexes

In [11]:
tseries = pd.Series(np.random.normal(10, 1, len(days)), index=days)
# Extracting elements
print (tseries[0:4], '\n')
print (tseries['2024-11-27':'2024-12-03'], '\n') # Note - includes end time

2024-11-27 10:45:00     9.394414
2024-11-28 10:45:00    10.347241
2024-11-29 10:45:00    11.404117
2024-11-30 10:45:00     9.120029
Freq: D, dtype: float64

2024-11-27 10:45:00     9.394414
2024-11-28 10:45:00    10.347241
2024-11-29 10:45:00    11.404117
2024-11-30 10:45:00     9.120029
2024-12-01 10:45:00     9.808430
2024-12-02 10:45:00     9.307590
2024-12-03 10:45:00    10.742856
Freq: D, dtype: float64

`pd.to_datetime` can also be used to create a `DatetimeIndex`:

In [12]:
pd.to_datetime([1, 2, 3, 4], unit='D', origin=pd.Timestamp('1980-02-03'))

DatetimeIndex(['1980-02-04', '1980-02-05', '1980-02-06', '1980-02-07'], dtype='datetime64[ns]', freq=None)

## DataFrame

A pandas DataFrame is like a simple tabular spreadsheet. For future reference (or for people already familiar with R), a pandas DataFrame is very similar to the R DataFrame.

Each column in a DataFrame is a Series object.

The element can be whatever, missing data are dealt with too (as NaN)

### DataFrame creation

A DataFrame can be created implicitly, with, e.g., a DatatimeIndex object as index:

In [13]:
entries=10
dates=pd.date_range('11/27/2024 10:45:00',freq='h', periods=entries)
df = pd.DataFrame(np.random.randn(entries,4), index=dates, columns=['A','B','C','D'])
df

                            A         B         C         D
2024-11-27 10:45:00 -0.960592  0.628543 -0.286222 -1.674104
2024-11-27 11:45:00 -0.233267 -1.210797 -0.414354 -0.283720
2024-11-27 12:45:00  0.315824 -0.702816  0.073538  1.732446
2024-11-27 13:45:00  0.189469  0.948628  0.667571 -0.863529
2024-11-27 14:45:00  0.367062 -0.121531  0.086231 -1.434398
2024-11-27 15:45:00  2.090991 -2.043441 -0.971572  0.299983
2024-11-27 16:45:00  1.088573  0.950472  0.809566 -2.062438
2024-11-27 17:45:00 -0.517549  0.459869 -1.418868  0.974099
2024-11-27 18:45:00 -0.021285  1.830536  1.361537  0.563070
2024-11-27 19:45:00  0.668036 -1.259794 -0.974985  2.300730

or by means of a dictionary:

In [14]:
df2 = pd.DataFrame(
    { 'A' : 1.,
      'B' : pd.Timestamp('20130102'),
      'C' : pd.Series(1,index=range(4),dtype='float32'),
      'D' : np.arange(7,11),
      'E' : pd.Categorical(["test","train","test","train"]),
    }
    )
df2

# check what happens if D and E had different lenghts

     A          B    C   D      E
0  1.0 2013-01-02  1.0   7   test
1  1.0 2013-01-02  1.0   8  train
2  1.0 2013-01-02  1.0   9   test
3  1.0 2013-01-02  1.0  10  train

### Viewing Data

In [15]:
df.head(2)

                            A         B         C         D
2024-11-27 10:45:00 -0.960592  0.628543 -0.286222 -1.674104
2024-11-27 11:45:00 -0.233267 -1.210797 -0.414354 -0.283720

In [16]:
df.tail(4)

                            A         B         C         D
2024-11-27 16:45:00  1.088573  0.950472  0.809566 -2.062438
2024-11-27 17:45:00 -0.517549  0.459869 -1.418868  0.974099
2024-11-27 18:45:00 -0.021285  1.830536  1.361537  0.563070
2024-11-27 19:45:00  0.668036 -1.259794 -0.974985  2.300730

In [17]:
df.index

DatetimeIndex(['2024-11-27 10:45:00', '2024-11-27 11:45:00',
               '2024-11-27 12:45:00', '2024-11-27 13:45:00',
               '2024-11-27 14:45:00', '2024-11-27 15:45:00',
               '2024-11-27 16:45:00', '2024-11-27 17:45:00',
               '2024-11-27 18:45:00', '2024-11-27 19:45:00'],
              dtype='datetime64[ns]', freq='h')

In [18]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [19]:
df.values

array([[-0.96059163,  0.62854331, -0.2862215 , -1.6741036 ],
       [-0.23326689, -1.21079718, -0.4143541 , -0.28372042],
       [ 0.3158237 , -0.70281638,  0.07353776,  1.73244632],
       [ 0.18946946,  0.94862836,  0.66757121, -0.86352879],
       [ 0.36706218, -0.12153073,  0.08623072, -1.43439819],
       [ 2.09099133, -2.04344079, -0.97157171,  0.29998267],
       [ 1.08857323,  0.95047234,  0.80956609, -2.062438  ],
       [-0.51754934,  0.45986923, -1.41886847,  0.97409887],
       [-0.02128486,  1.83053574,  1.36153652,  0.56306993],
       [ 0.66803555, -1.25979399, -0.97498484,  2.30072994]])

In [20]:
df.describe()

               A          B          C          D
count  10.000000  10.000000  10.000000  10.000000
mean    0.298726  -0.052033  -0.106756  -0.044786
std     0.858097   1.223434   0.882865   1.474620
min    -0.960592  -2.043441  -1.418868  -2.062438
25%    -0.180271  -1.083802  -0.832267  -1.291681
50%     0.252647   0.169169  -0.106342   0.008131
75%     0.592792   0.868607   0.522236   0.871342
max     2.090991   1.830536   1.361537   2.300730

In [21]:
df.T

,2024-11-27 10:45:00,2024-11-27 11:45:00,2024-11-27 12:45:00,2024-11-27 13:45:00,2024-11-27 14:45:00,2024-11-27 15:45:00,2024-11-27 16:45:00,2024-11-27 17:45:00,2024-11-27 18:45:00,2024-11-27 19:45:00
A,-0.960592,-0.233267,0.315824,0.189469,0.367062,2.090991,1.088573,-0.517549,-0.021285,0.668036
B,0.628543,-1.210797,-0.702816,0.948628,-0.121531,-2.043441,0.950472,0.459869,1.830536,-1.259794
C,-0.286222,-0.414354,0.073538,0.667571,0.086231,-0.971572,0.809566,-1.418868,1.361537,-0.974985
D,-1.674104,-0.283720,1.732446,-0.863529,-1.434398,0.299983,-2.062438,0.974099,0.563070,2.300730

In [22]:
df.sort_index(axis=0,ascending=False)

                            A         B         C         D
2024-11-27 19:45:00  0.668036 -1.259794 -0.974985  2.300730
2024-11-27 18:45:00 -0.021285  1.830536  1.361537  0.563070
2024-11-27 17:45:00 -0.517549  0.459869 -1.418868  0.974099
2024-11-27 16:45:00  1.088573  0.950472  0.809566 -2.062438
2024-11-27 15:45:00  2.090991 -2.043441 -0.971572  0.299983
2024-11-27 14:45:00  0.367062 -0.121531  0.086231 -1.434398
2024-11-27 13:45:00  0.189469  0.948628  0.667571 -0.863529
2024-11-27 12:45:00  0.315824 -0.702816  0.073538  1.732446
2024-11-27 11:45:00 -0.233267 -1.210797 -0.414354 -0.283720
2024-11-27 10:45:00 -0.960592  0.628543 -0.286222 -1.674104

In [23]:
df.sort_values(by="C")

                            A         B         C         D
2024-11-27 17:45:00 -0.517549  0.459869 -1.418868  0.974099
2024-11-27 19:45:00  0.668036 -1.259794 -0.974985  2.300730
2024-11-27 15:45:00  2.090991 -2.043441 -0.971572  0.299983
2024-11-27 11:45:00 -0.233267 -1.210797 -0.414354 -0.283720
2024-11-27 10:45:00 -0.960592  0.628543 -0.286222 -1.674104
2024-11-27 12:45:00  0.315824 -0.702816  0.073538  1.732446
2024-11-27 14:45:00  0.367062 -0.121531  0.086231 -1.434398
2024-11-27 13:45:00  0.189469  0.948628  0.667571 -0.863529
2024-11-27 16:45:00  1.088573  0.950472  0.809566 -2.062438
2024-11-27 18:45:00 -0.021285  1.830536  1.361537  0.563070

## Selection

### Getting slices

The following show how to get part of the DataFrame (i.e. not just the elements)

In [24]:
## standard and safe
print (df['A'],'\n')   # colonna 'A'

## equivalent but dangerous (imagine blank spaces in the name of the column..)
print (df.A)

2024-11-27 10:45:00   -0.960592
2024-11-27 11:45:00   -0.233267
2024-11-27 12:45:00    0.315824
2024-11-27 13:45:00    0.189469
2024-11-27 14:45:00    0.367062
2024-11-27 15:45:00    2.090991
2024-11-27 16:45:00    1.088573
2024-11-27 17:45:00   -0.517549
2024-11-27 18:45:00   -0.021285
2024-11-27 19:45:00    0.668036
Freq: h, Name: A, dtype: float64

2024-11-27 10:45:00   -0.960592
2024-11-27 11:45:00   -0.233267
2024-11-27 12:45:00    0.315824
2024-11-27 13:45:00    0.189469
2024-11-27 14:45:00    0.367062
2024-11-27 15:45:00    2.090991
2024-11-27 16:45:00    1.088573
2024-11-27 17:45:00   -0.517549
2024-11-27 18:45:00   -0.021285
2024-11-27 19:45:00    0.668036
Freq: h, Name: A, dtype: float64

In [25]:
# selecting rows by counting
print (df[0:3])

# or by index
print (df["2024-11-27 10:45:00":"2024-11-27 12:45:00"])

                            A         B         C         D
2024-11-27 10:45:00 -0.960592  0.628543 -0.286222 -1.674104
2024-11-27 11:45:00 -0.233267 -1.210797 -0.414354 -0.283720
2024-11-27 12:45:00  0.315824 -0.702816  0.073538  1.732446
                            A         B         C         D
2024-11-27 10:45:00 -0.960592  0.628543 -0.286222 -1.674104
2024-11-27 11:45:00 -0.233267 -1.210797 -0.414354 -0.283720
2024-11-27 12:45:00  0.315824 -0.702816  0.073538  1.732446

### Selection by label

In [26]:
# getting a cross section (part of the DataFrame) using a label
df.loc[dates[0]]  # mi restituisce le caselle con lo stesso indice (cioe insomma una riga)

A   -0.960592
B    0.628543
C   -0.286222
D   -1.674104
Name: 2024-11-27 10:45:00, dtype: float64

In [27]:
# selecting on a multi-axis by label:
df.loc[:,['A','B']]
#a=df.loc[:,['A','B']]

                            A         B
2024-11-27 10:45:00 -0.960592  0.628543
2024-11-27 11:45:00 -0.233267 -1.210797
2024-11-27 12:45:00  0.315824 -0.702816
2024-11-27 13:45:00  0.189469  0.948628
2024-11-27 14:45:00  0.367062 -0.121531
2024-11-27 15:45:00  2.090991 -2.043441
2024-11-27 16:45:00  1.088573  0.950472
2024-11-27 17:45:00 -0.517549  0.459869
2024-11-27 18:45:00 -0.021285  1.830536
2024-11-27 19:45:00  0.668036 -1.259794

In [28]:
# showing label slicing, both endpoints are included:
df.loc['2024-11-27 14:45:00':'2024-11-27 16:45:00',['A','B']]

                            A         B
2024-11-27 14:45:00  0.367062 -0.121531
2024-11-27 15:45:00  2.090991 -2.043441
2024-11-27 16:45:00  1.088573  0.950472

In [29]:
# getting an individual element
print (df.loc[dates[1],'A'])

# equivalently
print (df.at[dates[1],'A'])

-0.23326688856643163
-0.23326688856643163

### Selecting by position

In [30]:
# select via the position of the passed integers:
print (df.iloc[3],'\n')

# notation similar to numpy/python
print (df.iloc[3:5,0:2])

A    0.189469
B    0.948628
C    0.667571
D   -0.863529
Name: 2024-11-27 13:45:00, dtype: float64

                            A         B
2024-11-27 13:45:00  0.189469  0.948628
2024-11-27 14:45:00  0.367062 -0.121531

In [31]:
# selecting rows 1,2 and 4 for columns 0 and 2
df.iloc[[1,2,4],[0,2]]

                            A         C
2024-11-27 11:45:00 -0.233267 -0.414354
2024-11-27 12:45:00  0.315824  0.073538
2024-11-27 14:45:00  0.367062  0.086231

In [32]:
# slicing rows explicitly
print (df.iloc[1:3,:],'\n')

# slicing columns explicitly
print (df.iloc[:,1:3], '\n')

# selecting an individual element by position
print(df.iloc[1,1])

                            A         B         C         D
2024-11-27 11:45:00 -0.233267 -1.210797 -0.414354 -0.283720
2024-11-27 12:45:00  0.315824 -0.702816  0.073538  1.732446

                            B         C
2024-11-27 10:45:00  0.628543 -0.286222
2024-11-27 11:45:00 -1.210797 -0.414354
2024-11-27 12:45:00 -0.702816  0.073538
2024-11-27 13:45:00  0.948628  0.667571
2024-11-27 14:45:00 -0.121531  0.086231
2024-11-27 15:45:00 -2.043441 -0.971572
2024-11-27 16:45:00  0.950472  0.809566
2024-11-27 17:45:00  0.459869 -1.418868
2024-11-27 18:45:00  1.830536  1.361537
2024-11-27 19:45:00 -1.259794 -0.974985

-1.2107971820816243

### Boolean index

Very powerful way of filtering out data with certain features. Notation is very similar to numpy arrays.

In [33]:
# Filter by a boolean condition on the values of a single column
df[df['B'] > 0]   # it prints only the rows where the element on column B is positive

                            A         B         C         D
2024-11-27 10:45:00 -0.960592  0.628543 -0.286222 -1.674104
2024-11-27 13:45:00  0.189469  0.948628  0.667571 -0.863529
2024-11-27 16:45:00  1.088573  0.950472  0.809566 -2.062438
2024-11-27 17:45:00 -0.517549  0.459869 -1.418868  0.974099
2024-11-27 18:45:00 -0.021285  1.830536  1.361537  0.563070

In [34]:
# Selecting on the basis of boolean conditions applied to the whole DataFrame
df[df>0]

# a DataFrame with the same shape is returned, with NaN's where condition is not met

                            A         B         C         D
2024-11-27 10:45:00       NaN  0.628543       NaN       NaN
2024-11-27 11:45:00       NaN       NaN       NaN       NaN
2024-11-27 12:45:00  0.315824       NaN  0.073538  1.732446
2024-11-27 13:45:00  0.189469  0.948628  0.667571       NaN
2024-11-27 14:45:00  0.367062       NaN  0.086231       NaN
2024-11-27 15:45:00  2.090991       NaN       NaN  0.299983
2024-11-27 16:45:00  1.088573  0.950472  0.809566       NaN
2024-11-27 17:45:00       NaN  0.459869       NaN  0.974099
2024-11-27 18:45:00       NaN  1.830536  1.361537  0.563070
2024-11-27 19:45:00  0.668036       NaN       NaN  2.300730

### Setting

Combination of selection and setting of values

In [35]:
# setting values by label (same as by position)
df.at[dates[0],'A'] = 0

# setting and assigning a numpy array
df.loc[:,'D'] = np.array([5] * len(df))

# defining a brend new column
df['E'] = np.arange(len(df))*0.5

# defining a brend new column by means of a pd.Series: indexes must be the same!
df['E prime'] = pd.Series(np.arange(len(df))*2, index=df.index)

df

                            A         B         C    D    E  E prime
2024-11-27 10:45:00  0.000000  0.628543 -0.286222  5.0  0.0        0
2024-11-27 11:45:00 -0.233267 -1.210797 -0.414354  5.0  0.5        2
2024-11-27 12:45:00  0.315824 -0.702816  0.073538  5.0  1.0        4
2024-11-27 13:45:00  0.189469  0.948628  0.667571  5.0  1.5        6
2024-11-27 14:45:00  0.367062 -0.121531  0.086231  5.0  2.0        8
2024-11-27 15:45:00  2.090991 -2.043441 -0.971572  5.0  2.5       10
2024-11-27 16:45:00  1.088573  0.950472  0.809566  5.0  3.0       12
2024-11-27 17:45:00 -0.517549  0.459869 -1.418868  5.0  3.5       14
2024-11-27 18:45:00 -0.021285  1.830536  1.361537  5.0  4.0       16
2024-11-27 19:45:00  0.668036 -1.259794 -0.974985  5.0  4.5       18

In [36]:
def dcos(theta):
    theta = theta*(np.pi/180)
    return np.cos(theta)
 
df['cosine'] = pd.Series(df["E"].apply(dcos), index=df.index)
df

                            A         B         C    D    E  E prime    cosine
2024-11-27 10:45:00  0.000000  0.628543 -0.286222  5.0  0.0        0  1.000000
2024-11-27 11:45:00 -0.233267 -1.210797 -0.414354  5.0  0.5        2  0.999962
2024-11-27 12:45:00  0.315824 -0.702816  0.073538  5.0  1.0        4  0.999848
2024-11-27 13:45:00  0.189469  0.948628  0.667571  5.0  1.5        6  0.999657
2024-11-27 14:45:00  0.367062 -0.121531  0.086231  5.0  2.0        8  0.999391
2024-11-27 15:45:00  2.090991 -2.043441 -0.971572  5.0  2.5       10  0.999048
2024-11-27 16:45:00  1.088573  0.950472  0.809566  5.0  3.0       12  0.998630
2024-11-27 17:45:00 -0.517549  0.459869 -1.418868  5.0  3.5       14  0.998135
2024-11-27 18:45:00 -0.021285  1.830536  1.361537  5.0  4.0       16  0.997564
2024-11-27 19:45:00  0.668036 -1.259794 -0.974985  5.0  4.5       18  0.996917

In [37]:
# another example of global setting
df2=df.copy()

df2[df2>0] = -df2
df2

                            A         B         C    D    E  E prime    cosine
2024-11-27 10:45:00  0.000000 -0.628543 -0.286222 -5.0  0.0        0 -1.000000
2024-11-27 11:45:00 -0.233267 -1.210797 -0.414354 -5.0 -0.5       -2 -0.999962
2024-11-27 12:45:00 -0.315824 -0.702816 -0.073538 -5.0 -1.0       -4 -0.999848
2024-11-27 13:45:00 -0.189469 -0.948628 -0.667571 -5.0 -1.5       -6 -0.999657
2024-11-27 14:45:00 -0.367062 -0.121531 -0.086231 -5.0 -2.0       -8 -0.999391
2024-11-27 15:45:00 -2.090991 -2.043441 -0.971572 -5.0 -2.5      -10 -0.999048
2024-11-27 16:45:00 -1.088573 -0.950472 -0.809566 -5.0 -3.0      -12 -0.998630
2024-11-27 17:45:00 -0.517549 -0.459869 -1.418868 -5.0 -3.5      -14 -0.998135
2024-11-27 18:45:00 -0.021285 -1.830536 -1.361537 -5.0 -4.0      -16 -0.997564
2024-11-27 19:45:00 -0.668036 -1.259794 -0.974985 -5.0 -4.5      -18 -0.996917

### Are you dealing with a Copy or a View?

In general is hard to tell..

In [38]:
dfd = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6]})

# This is likely a view
subset = dfd.loc[0:1, 'a']  
subset[0] = 100  # May affect `df`

print (dfd)

# This is a copy
subset = dfd.loc[[0, 1], 'a']  
subset[0] = 200  # Does NOT affect `df`

print (dfd)

     a  b
0  100  4
1    2  5
2    3  6
     a  b
0  100  4
1    2  5
2    3  6

The behaviour depend on the version of Pandas and on the version of Numpy that given version of Pandas depends upon. Since Pandas 1.5 "Copy-on-Write" (CoW) is (optionally) available and as of Pandas 3.0 will be the default. 

With CoW chained assignemt will never work; in the following example, the view `df["foo"]` and `df` itself are modified in one step. This will lead to a `ChainedAssignemntError`

In [39]:
dfd["a"][dfd["b"] > 5] = 100
dfd

/tmp/ipykernel_5368/449088826.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dfd["a"][dfd["b"] > 5] = 100

     a  b
0  100  4
1    2  5
2  100  6

With copy on write this can be done by using `loc`

In [40]:
dfd.loc[dfd["b"] > 5, "a"] = 200
dfd

     a  b
0  100  4
1    2  5
2  200  6

### Dropping

N.B.: dropping doesn't act permanently on the DataFrame, i.e. to get that do :
```python
df = df.drop(....)
```

In [41]:
# Dropping by column
df.drop(['E prime'], axis=1)

#which is equivalent to
new_df=df.drop(columns=['E prime'])
new_df

                            A         B         C    D    E    cosine
2024-11-27 10:45:00  0.000000  0.628543 -0.286222  5.0  0.0  1.000000
2024-11-27 11:45:00 -0.233267 -1.210797 -0.414354  5.0  0.5  0.999962
2024-11-27 12:45:00  0.315824 -0.702816  0.073538  5.0  1.0  0.999848
2024-11-27 13:45:00  0.189469  0.948628  0.667571  5.0  1.5  0.999657
2024-11-27 14:45:00  0.367062 -0.121531  0.086231  5.0  2.0  0.999391
2024-11-27 15:45:00  2.090991 -2.043441 -0.971572  5.0  2.5  0.999048
2024-11-27 16:45:00  1.088573  0.950472  0.809566  5.0  3.0  0.998630
2024-11-27 17:45:00 -0.517549  0.459869 -1.418868  5.0  3.5  0.998135
2024-11-27 18:45:00 -0.021285  1.830536  1.361537  5.0  4.0  0.997564
2024-11-27 19:45:00  0.668036 -1.259794 -0.974985  5.0  4.5  0.996917

In [42]:
# Dropping by raws
# safe and always working
df.drop(df.index[[1,2,3,4]])

                            A         B         C    D    E  E prime    cosine
2024-11-27 10:45:00  0.000000  0.628543 -0.286222  5.0  0.0        0  1.000000
2024-11-27 15:45:00  2.090991 -2.043441 -0.971572  5.0  2.5       10  0.999048
2024-11-27 16:45:00  1.088573  0.950472  0.809566  5.0  3.0       12  0.998630
2024-11-27 17:45:00 -0.517549  0.459869 -1.418868  5.0  3.5       14  0.998135
2024-11-27 18:45:00 -0.021285  1.830536  1.361537  5.0  4.0       16  0.997564
2024-11-27 19:45:00  0.668036 -1.259794 -0.974985  5.0  4.5       18  0.996917

In [43]:
df

                            A         B         C    D    E  E prime    cosine
2024-11-27 10:45:00  0.000000  0.628543 -0.286222  5.0  0.0        0  1.000000
2024-11-27 11:45:00 -0.233267 -1.210797 -0.414354  5.0  0.5        2  0.999962
2024-11-27 12:45:00  0.315824 -0.702816  0.073538  5.0  1.0        4  0.999848
2024-11-27 13:45:00  0.189469  0.948628  0.667571  5.0  1.5        6  0.999657
2024-11-27 14:45:00  0.367062 -0.121531  0.086231  5.0  2.0        8  0.999391
2024-11-27 15:45:00  2.090991 -2.043441 -0.971572  5.0  2.5       10  0.999048
2024-11-27 16:45:00  1.088573  0.950472  0.809566  5.0  3.0       12  0.998630
2024-11-27 17:45:00 -0.517549  0.459869 -1.418868  5.0  3.5       14  0.998135
2024-11-27 18:45:00 -0.021285  1.830536  1.361537  5.0  4.0       16  0.997564
2024-11-27 19:45:00  0.668036 -1.259794 -0.974985  5.0  4.5       18  0.996917

In [44]:
# something like df.drop('index_name') 
# would work but the type of index must be specificed, 
# in particular with DatetimeIndex
df.drop(pd.to_datetime("2024-11-27 18:45:00"))

                            A         B         C    D    E  E prime    cosine
2024-11-27 10:45:00  0.000000  0.628543 -0.286222  5.0  0.0        0  1.000000
2024-11-27 11:45:00 -0.233267 -1.210797 -0.414354  5.0  0.5        2  0.999962
2024-11-27 12:45:00  0.315824 -0.702816  0.073538  5.0  1.0        4  0.999848
2024-11-27 13:45:00  0.189469  0.948628  0.667571  5.0  1.5        6  0.999657
2024-11-27 14:45:00  0.367062 -0.121531  0.086231  5.0  2.0        8  0.999391
2024-11-27 15:45:00  2.090991 -2.043441 -0.971572  5.0  2.5       10  0.999048
2024-11-27 16:45:00  1.088573  0.950472  0.809566  5.0  3.0       12  0.998630
2024-11-27 17:45:00 -0.517549  0.459869 -1.418868  5.0  3.5       14  0.998135
2024-11-27 19:45:00  0.668036 -1.259794 -0.974985  5.0  4.5       18  0.996917

## Missing data

pandas primarily uses the value np.nan to represent missing data. It is by default not included in computations.

In [45]:
df_wNan = df[df>0]
df_wNan

                            A         B         C    D    E  E prime    cosine
2024-11-27 10:45:00       NaN  0.628543       NaN  5.0  NaN      NaN  1.000000
2024-11-27 11:45:00       NaN       NaN       NaN  5.0  0.5      2.0  0.999962
2024-11-27 12:45:00  0.315824       NaN  0.073538  5.0  1.0      4.0  0.999848
2024-11-27 13:45:00  0.189469  0.948628  0.667571  5.0  1.5      6.0  0.999657
2024-11-27 14:45:00  0.367062       NaN  0.086231  5.0  2.0      8.0  0.999391
2024-11-27 15:45:00  2.090991       NaN       NaN  5.0  2.5     10.0  0.999048
2024-11-27 16:45:00  1.088573  0.950472  0.809566  5.0  3.0     12.0  0.998630
2024-11-27 17:45:00       NaN  0.459869       NaN  5.0  3.5     14.0  0.998135
2024-11-27 18:45:00       NaN  1.830536  1.361537  5.0  4.0     16.0  0.997564
2024-11-27 19:45:00  0.668036       NaN       NaN  5.0  4.5     18.0  0.996917

In [46]:
# dropping raws with at least a Nan
df_wNan.dropna(how='any')

                            A         B         C    D    E  E prime    cosine
2024-11-27 13:45:00  0.189469  0.948628  0.667571  5.0  1.5      6.0  0.999657
2024-11-27 16:45:00  1.088573  0.950472  0.809566  5.0  3.0     12.0  0.998630

In [47]:
# getting a mask
df_wNan.isna()
#df_wNan.notna()

                         A      B      C      D      E  E prime  cosine
2024-11-27 10:45:00   True  False   True  False   True     True   False
2024-11-27 11:45:00   True   True   True  False  False    False   False
2024-11-27 12:45:00  False   True  False  False  False    False   False
2024-11-27 13:45:00  False  False  False  False  False    False   False
2024-11-27 14:45:00  False   True  False  False  False    False   False
2024-11-27 15:45:00  False   True   True  False  False    False   False
2024-11-27 16:45:00  False  False  False  False  False    False   False
2024-11-27 17:45:00   True  False   True  False  False    False   False
2024-11-27 18:45:00   True  False  False  False  False    False   False
2024-11-27 19:45:00  False   True   True  False  False    False   False

In [48]:
# filling missing data
df_wNan.fillna(value=0)

                            A         B         C    D    E  E prime    cosine
2024-11-27 10:45:00  0.000000  0.628543  0.000000  5.0  0.0      0.0  1.000000
2024-11-27 11:45:00  0.000000  0.000000  0.000000  5.0  0.5      2.0  0.999962
2024-11-27 12:45:00  0.315824  0.000000  0.073538  5.0  1.0      4.0  0.999848
2024-11-27 13:45:00  0.189469  0.948628  0.667571  5.0  1.5      6.0  0.999657
2024-11-27 14:45:00  0.367062  0.000000  0.086231  5.0  2.0      8.0  0.999391
2024-11-27 15:45:00  2.090991  0.000000  0.000000  5.0  2.5     10.0  0.999048
2024-11-27 16:45:00  1.088573  0.950472  0.809566  5.0  3.0     12.0  0.998630
2024-11-27 17:45:00  0.000000  0.459869  0.000000  5.0  3.5     14.0  0.998135
2024-11-27 18:45:00  0.000000  1.830536  1.361537  5.0  4.0     16.0  0.997564
2024-11-27 19:45:00  0.668036  0.000000  0.000000  5.0  4.5     18.0  0.996917

Fill gaps forward or backward by propagating non-NA values forward or backward:

In [49]:
df_wNan.fillna(method='pad')

/tmp/ipykernel_5368/1387294891.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_wNan.fillna(method='pad')

                            A         B         C    D    E  E prime    cosine
2024-11-27 10:45:00       NaN  0.628543       NaN  5.0  NaN      NaN  1.000000
2024-11-27 11:45:00       NaN  0.628543       NaN  5.0  0.5      2.0  0.999962
2024-11-27 12:45:00  0.315824  0.628543  0.073538  5.0  1.0      4.0  0.999848
2024-11-27 13:45:00  0.189469  0.948628  0.667571  5.0  1.5      6.0  0.999657
2024-11-27 14:45:00  0.367062  0.948628  0.086231  5.0  2.0      8.0  0.999391
2024-11-27 15:45:00  2.090991  0.948628  0.086231  5.0  2.5     10.0  0.999048
2024-11-27 16:45:00  1.088573  0.950472  0.809566  5.0  3.0     12.0  0.998630
2024-11-27 17:45:00  1.088573  0.459869  0.809566  5.0  3.5     14.0  0.998135
2024-11-27 18:45:00  1.088573  1.830536  1.361537  5.0  4.0     16.0  0.997564
2024-11-27 19:45:00  0.668036  1.830536  1.361537  5.0  4.5     18.0  0.996917

## Operations

Here comes the most relevant advantage of DataFrame. Operations on columns are extremly fast due to several intrinsic optimizations.

* They are implemented in C/Cython via NumPy.
* Pandas processes columns as contiguous memory arrays.
* Vectorized operations eliminate the need for slow Python loops.
* Efficient memory and cache utilization boost performance.

In [50]:
# Some statistics (mean() just as an example)
# rows
print (df.mean(axis=0),'\n')
# columns
print (df.mean(axis=1),'\n')

A          0.394785
B         -0.052033
C         -0.106756
D          5.000000
E          2.250000
E prime    9.000000
cosine     0.998915
dtype: float64

2024-11-27 10:45:00    0.906046
2024-11-27 11:45:00    0.948792
2024-11-27 12:45:00    1.526628
2024-11-27 13:45:00    2.186475
2024-11-27 14:45:00    2.333022
2024-11-27 15:45:00    2.510718
2024-11-27 16:45:00    3.406749
2024-11-27 17:45:00    3.145941
2024-11-27 18:45:00    4.166907
2024-11-27 19:45:00    3.847168
Freq: h, dtype: float64

In [ ]:
# global operations on columns
df.apply(np.cumsum)

In [ ]:
df

In [ ]:
df.apply(lambda x: x.max() - x.min())

In [ ]:
# syntax is as usual similar to that of numpy arrays
df['A']+df['B']

Let's play it hard and load (in memory) a (relatively) large dataset

In [ ]:
# WARNING! link in past notebook was wrong!, (if needed) get the right file from:
#!wget https://www.dropbox.com/s/xvjzaxzz3ysphme/data_000637.txt -P ~/data/

file_name="~/data/data_000637.txt"
data=pd.read_csv(file_name)
data.tail(10)

Let's now do some operations among (elements of) columns

In [ ]:
# the one-liner killing it all
data['timens']=data['TDC_MEAS']*25/30+data['BX_COUNTER']*25

In [ ]:
data['timens']

In [ ]:
# the old slooow way
def conversion(data):
    result=[]
    for i in range(len(data)): 
        result.append(data.loc[data.index[i],'TDC_MEAS']*25/30.+data.loc[data.index[i],'BX_COUNTER']*25)
    return result

data['timens']=conversion(data)

For tasks on extremely large datasets, libraries like [Polars](https://docs.pola.rs) or [Dask](https://www.dask.org) can offer even faster alternatives by further parallelizing or optimizing columnar operations.

## Merge

Pandas provides various facilities for easily combining together Series, DataFrame, and Panel objects with various kinds of set logic for the indexes and relational algebra functionality in the case of join / merge-type operations.

### Concat

concatenation (adding rows) is straightforward

In [52]:
rdf = pd.DataFrame(np.random.randn(10, 4))
rdf

          0         1         2         3
0 -0.222790 -0.385043 -0.642307 -0.094775
1  0.885680 -0.293833 -2.603943  0.559543
2 -0.044623 -0.704337 -0.197697  0.544431
3  0.023641 -0.546925  1.735531  1.336173
4 -1.481601 -0.060092 -0.601566 -0.101680
5  0.715445  0.407541 -0.530008 -0.093040
6  0.702404 -0.380682 -0.888750  0.070583
7 -0.011205 -0.793096  0.282678  0.305342
8  0.578477 -0.348841  0.792231  0.161359
9 -1.553559 -0.364136  0.588106 -0.064848

In [53]:
# divide it into pieces row-wise
pieces = [rdf[:3], rdf[3:7], rdf[7:]]
pieces

[          0         1         2         3
 0 -0.222790 -0.385043 -0.642307 -0.094775
 1  0.885680 -0.293833 -2.603943  0.559543
 2 -0.044623 -0.704337 -0.197697  0.544431,
           0         1         2         3
 3  0.023641 -0.546925  1.735531  1.336173
 4 -1.481601 -0.060092 -0.601566 -0.101680
 5  0.715445  0.407541 -0.530008 -0.093040
 6  0.702404 -0.380682 -0.888750  0.070583,
           0         1         2         3
 7 -0.011205 -0.793096  0.282678  0.305342
 8  0.578477 -0.348841  0.792231  0.161359
 9 -1.553559 -0.364136  0.588106 -0.064848]

In [54]:
# put it back together
#pd.concat(pieces)

# indexes can be ignored
pd.concat(pieces, ignore_index=True)

# in case of dimension mismatch, Nan are added where needed

          0         1         2         3
0 -0.222790 -0.385043 -0.642307 -0.094775
1  0.885680 -0.293833 -2.603943  0.559543
2 -0.044623 -0.704337 -0.197697  0.544431
3  0.023641 -0.546925  1.735531  1.336173
4 -1.481601 -0.060092 -0.601566 -0.101680
5  0.715445  0.407541 -0.530008 -0.093040
6  0.702404 -0.380682 -0.888750  0.070583
7 -0.011205 -0.793096  0.282678  0.305342
8  0.578477 -0.348841  0.792231  0.161359
9 -1.553559 -0.364136  0.588106 -0.064848

In [55]:
# appending a single row (as a Series)
s = rdf.iloc[3]
rdf = pd.concat([rdf,s.to_frame().T], ignore_index=True)
rdf

           0         1         2         3
0  -0.222790 -0.385043 -0.642307 -0.094775
1   0.885680 -0.293833 -2.603943  0.559543
2  -0.044623 -0.704337 -0.197697  0.544431
3   0.023641 -0.546925  1.735531  1.336173
4  -1.481601 -0.060092 -0.601566 -0.101680
5   0.715445  0.407541 -0.530008 -0.093040
6   0.702404 -0.380682 -0.888750  0.070583
7  -0.011205 -0.793096  0.282678  0.305342
8   0.578477 -0.348841  0.792231  0.161359
9  -1.553559 -0.364136  0.588106 -0.064848
10  0.023641 -0.546925  1.735531  1.336173

### Merge/Join

SQL like operations on table can be performed on DataFrames. This is all rather sophisticated, refer to the [doc](https://pandas.pydata.org/pandas-docs/stable/merging.html#merging) for more info/examples.

#### Merging, Inner Join (default)

Only rows with matching id values are included:

In [56]:
import pandas as pd

df1 = pd.DataFrame({'id': [1, 2, 3], 'name': ['Alice', 'Bob', 'Charlie']})
df2 = pd.DataFrame({'id': [2, 3, 4], 'age': [25, 30, 35]})

# Merge on the 'id' column
result = pd.merge(df1, df2, on='id')
print(result)

   id     name  age
0   2      Bob   25
1   3  Charlie   30

#### Merging, Left Join

A left join includes all rows from `df1` (left) and fills in `NaN` for missing matches in `df2`.

In [57]:
result = pd.merge(df1, df2, on='id', how='left')
print(result)

   id     name   age
0   1    Alice   NaN
1   2      Bob  25.0
2   3  Charlie  30.0

#### Merging, Outer Join

An outer join includes all rows from both DataFrames, filling NaN for missing values

In [58]:
result = pd.merge(df1, df2, on='id', how='outer')
print(result)

   id     name   age
0   1    Alice   NaN
1   2      Bob  25.0
2   3  Charlie  30.0
3   4      NaN  35.0

`join` is similar to `merge` but uses index as key and has 'Left' as default

In [59]:
df1 = pd.DataFrame({'name': ['Alice', 'Bob', 'Charlie']}, index=[1, 2, 3])
df2 = pd.DataFrame({'age': [25, 30, 35]}, index=[2, 3, 4])

result = df1.join(df2)
print(result)

      name   age
1    Alice   NaN
2      Bob  25.0
3  Charlie  30.0

## Grouping

By “group by” we are referring to a process involving one or more of the following steps:

* Splitting the data into groups based on some criteria
* Applying a function to each group independently
* Combining the results into a data structure


Grouping is one of the most powerful and at the same time most sofisticated action you can perform with DataFrames. Mastering it is key for an effective usage of Pandas and vectorized data analysis. Reading the [documentation](https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html) or going through a [tutorial](https://realpython.com/pandas-groupby/) is warmly recommended. 

Let's go through a few examples:

In [24]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'C'],
    'Values': [10, 20, 30, 40, 50, 60]
}

df = pd.DataFrame(data)

# Group by 'Category' and calculate the sum of their 'Values'
result = df.groupby('Category').sum()
print(result)

df

          Values
Category
A             90
B             60
C             60

  Category  Values
0        A      10
1        B      20
2        A      30
3        B      40
4        A      50
5        C      60

In [26]:
# Multiple Aggregations
result = df.groupby('Category').agg(['sum', 'mean'])   # sum e mean sono dei metodi veri e propri, non puoi chiamarli in altro modo!!
print(result)

         Values
            sum  mean
Category
A            90  30.0
B            60  30.0
C            60  60.0

In [27]:
# Grouping by multiple columns
df = pd.DataFrame({'Category': ['A', 'A', 'B', 'B', 'C', 'C'],
                   'Type': ['X', 'Y', 'X', 'Y', 'X', 'Y'],
                   'Values': [10, 20, 30, 40, 50, 60]})

result = df.groupby(['Category', 'Type']).sum()
print(result)

result = df.groupby(['Type', 'Category']).sum()
print(result)

result = df.groupby(['Values', 'Category']).sum()
print(result)
df

               Values
Category Type
A        X         10
         Y         20
B        X         30
         Y         40
C        X         50
         Y         60
               Values
Type Category
X    A             10
     B             30
     C             50
Y    A             20
     B             40
     C             60
                Type
Values Category
10     A           X
20     A           Y
30     B           X
40     B           Y
50     C           X
60     C           Y

  Category Type  Values
0        A    X      10
1        A    Y      20
2        B    X      30
3        B    Y      40
4        C    X      50
5        C    Y      60

In [28]:
# Trasformations using groupby(): add group averages to DataFrame

# la seguente riga calcola la media 'mean' della colonna 'Values' per ogni gruppo in Category e la assegna a una nuova colonna 'Group_Avg', 
    # replicando il valore medio per ogni riga del gruppo
df['Group_Avg'] = df.groupby('Category')['Values'].transform('mean')
print(df)

  Category Type  Values  Group_Avg
0        A    X      10       15.0
1        A    Y      20       15.0
2        B    X      30       35.0
3        B    Y      40       35.0
4        C    X      50       55.0
5        C    Y      60       55.0

In [29]:
# filtering
filtered = df.groupby('Category').filter(lambda x: x['Values'].sum() > 50)
print(filtered)

  Category Type  Values  Group_Avg
2        B    X      30       35.0
3        B    Y      40       35.0
4        C    X      50       55.0
5        C    Y      60       55.0

In [30]:
# custom aggregation with apply()
def custom_aggregation(group):
    return pd.Series({
        'Sum': group['Values'].sum(),
        'Max': group['Values'].max(),
        'Count': group['Values'].count()
    })

result = df.groupby('Category').apply(custom_aggregation)
print(result)

          Sum  Max  Count
Category
A          30   20      2
B          70   40      2
C         110   60      2

/tmp/ipykernel_4482/640594234.py:9: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df.groupby('Category').apply(custom_aggregation)

In [36]:
# splitting data into groups
grouped = df.groupby('Category')

for name, group in grouped:
    print(f"Group: {name}")
    print(group)

Group: A
  Category Type  Values  Group_Avg
0        A    X      10       15.0
1        A    Y      20       15.0
Group: B
  Category Type  Values  Group_Avg
2        B    X      30       35.0
3        B    Y      40       35.0
Group: C
  Category Type  Values  Group_Avg
4        C    X      50       55.0
5        C    Y      60       55.0

## Multi-indexing


Hierarchical / Multi-level indexing allows sophisticated data analysis on higher dimensional data. In essence, it enables you to store and manipulate data with an arbitrary number of dimensions in lower dimensional data structures like Series (1d) and DataFrame (2d).

In [60]:
tuples = list(zip(['bar', 'bar', 'baz', 'baz', 'foo', 'foo', 'qux', 'qux'],
          ['one', 'two', 'one', 'two', 'one', 'two', 'one', 'two']))
multi_index = pd.MultiIndex.from_tuples(tuples, names=['first', 'second'])
print (multi_index,'\n')

s = pd.Series(np.random.randn(8), index=multi_index)
print (s)

MultiIndex([('bar', 'one'),
            ('bar', 'two'),
            ('baz', 'one'),
            ('baz', 'two'),
            ('foo', 'one'),
            ('foo', 'two'),
            ('qux', 'one'),
            ('qux', 'two')],
           names=['first', 'second'])

first  second
bar    one       1.671093
       two      -0.637538
baz    one      -0.159100
       two      -0.581413
foo    one      -0.350622
       two      -0.967872
qux    one      -0.128637
       two      -0.655500
dtype: float64

In [61]:
gdf = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar',
                          'foo', 'bar', 'foo', 'foo'],
                    'B' : ['one', 'one', 'two', 'three',
                           'two', 'two', 'one', 'three'],
                    'C' : np.random.randn(8),
                    'D' : np.random.randn(8)})
gdf

# it enables further features of the groupby method,
# e.g. when group-by by multiple columns
gdf.groupby(['A','B']).sum()

                  C         D
A   B
bar one    1.150949 -0.770124
    three  0.418791  0.577088
    two   -0.711057  0.475433
foo one    1.886410  0.033543
    three  0.302509 -0.498837
    two    0.003047 -1.096727

In [62]:
# stack() method “compresses” a level in the DataFrame’s columns
gdf.groupby(['A','B']).sum().stack()

A    B
bar  one    C    1.150949
            D   -0.770124
     three  C    0.418791
            D    0.577088
     two    C   -0.711057
            D    0.475433
foo  one    C    1.886410
            D    0.033543
     three  C    0.302509
            D   -0.498837
     two    C    0.003047
            D   -1.096727
dtype: float64

## Plotting

Just a preview, more on the next lab class!

In [ ]:
ts = pd.Series(np.random.randn(1000), index=pd.date_range('1/1/2000', periods=1000))
ts.cumsum().plot()

In [ ]:
import matplotlib.pyplot as plt

pdf=pd.DataFrame(np.random.randn(1000, 4), index=ts.index,columns=['A', 'B', 'C', 'D'])
pdf = pdf.cumsum()
plt.figure(); pdf.plot(); plt.legend(loc='best')